name: "pnpm"
description: "Set up pnpm and install dependencies"

inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: 22.5.1

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda

    - name: Set up node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: pnpm install

